### PR TITLE
Brainloss is on the brain organ

### PR DESCRIPTION
**Pull request by JJRcop**
This changes brainloss to be stored as damage to the brain organ. I would ask maintainers to check out this PR themselves before you merge it into tgstation/tgstation#31727, since they might not like it.

or forget about them and merge it anyway if you want, you the man

### CODE REVIEW

**Comment by JJRcop** [comment]
This has the effect of too much brainloss destroying the brain. Currently 400 brainloss will do this.

**Comment by XDTM** [comment]
I'd rather make it so the brain is unusable after 200 brain damage, instead of deleting it outright. Otherwise, great stuff.

**Comment by JJRcop** [comment]
That is still the case, but too much brain damage (400 right now, 200 more than what kills you and makes the brain unusable) destroys the brain. This can be tweaked, the brain can also be modified to not get destroyed. If you want I can tweak it so that 600 brain damage does this, or 800, 1000, etc

**Comment by XDTM** [comment]
400 seems alright, i think it can be interpreted as the brain turning into straight mush. Now i also have to port traumas in there, or it'll be kinda pointless.

**Comment by JJRcop** [comment]
Traumas still work, I tested, what do you mean?

**Pull request merged**
